-- ==============================================================================
-- 1. ENUMS (Tipos Enumerados)
-- ==============================================================================

CREATE TYPE "Scope" AS ENUM ('INDIVIDUAL', 'SETORIAL');
CREATE TYPE "ServiceOrderStatus" AS ENUM ('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA');
CREATE TYPE "Priority" AS ENUM ('BAIXA', 'MEDIA', 'ALTA');
CREATE TYPE "PendencyType" AS ENUM ('OS', 'FINANCEIRO', 'ADMINISTRATIVO', 'TI', 'COMERCIAL', 'OUTRO');
CREATE TYPE "PendencyStatus" AS ENUM ('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO', 'ENCERRADA_SEM_CONCLUSAO');
CREATE TYPE "OriginType" AS ENUM ('MANUAL', 'OS');
CREATE TYPE "ConclusionType" AS ENUM ('CONCLUIDO', 'SEM_CONCLUSAO');

-- ==============================================================================
-- 2. TABELAS BASE
-- ==============================================================================

-- Tabela: users
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "parameters" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- Index Unique para email
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");


-- Tabela: roles
CREATE TABLE "roles" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "is_system" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);


-- Tabela: permissions
CREATE TABLE "permissions" (
    "id" TEXT NOT NULL,
    "description" TEXT,

    CONSTRAINT "permissions_pkey" PRIMARY KEY ("id")
);


-- Tabela: sectors
CREATE TABLE "sectors" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sectors_pkey" PRIMARY KEY ("id")
);


-- Tabela: positions
CREATE TABLE "positions" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "scope" "Scope" NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "positions_pkey" PRIMARY KEY ("id")
);


-- Tabela: system_configs (Singleton)
CREATE TABLE "system_configs" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "config" JSONB NOT NULL,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "system_configs_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "system_configs_singleton" CHECK (id = 1)
);


-- Tabela: audit_events
-- actor_id NÃO POSSUI FOREIGN KEY EXPLICITA PARA EVITAR PERDA DE LOGS SE USUARIO FOR DELETADO.
-- MANTIDO COMO STRING NOT NULL PARA REFERENCIA HISTORICA.
CREATE TABLE "audit_events" (
    "id" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "level" TEXT NOT NULL,
    "event" TEXT NOT NULL,
    "actor_id" TEXT NOT NULL,
    "target_id" TEXT,
    "ip" TEXT,
    "details" JSONB,

    CONSTRAINT "audit_events_pkey" PRIMARY KEY ("id")
);


-- Tabela: service_orders
CREATE TABLE "service_orders" (
    "id" TEXT NOT NULL,
    "number" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "client_data" JSONB NOT NULL,
    "status" "ServiceOrderStatus" NOT NULL DEFAULT 'ABERTA',
    "priority" "Priority" NOT NULL DEFAULT 'MEDIA',
    "description" TEXT NOT NULL,
    "scheduled_date" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "service_orders_pkey" PRIMARY KEY ("id")
);

-- ==============================================================================
-- 3. TABELAS DE RELACIONAMENTO E DEPENDENTES
-- ==============================================================================

-- Tabela Associativa: users_roles
CREATE TABLE "users_roles" (
    "user_id" TEXT NOT NULL,
    "role_id" TEXT NOT NULL,

    CONSTRAINT "users_roles_pkey" PRIMARY KEY ("user_id", "role_id"),
    CONSTRAINT "users_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "users_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE
);


-- Tabela Associativa: roles_permissions
CREATE TABLE "roles_permissions" (
    "role_id" TEXT NOT NULL,
    "permission_id" TEXT NOT NULL,

    CONSTRAINT "roles_permissions_pkey" PRIMARY KEY ("role_id", "permission_id"),
    CONSTRAINT "roles_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "roles_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE
);


-- Tabela Associativa: positions_sectors
CREATE TABLE "positions_sectors" (
    "position_id" TEXT NOT NULL,
    "sector_id" TEXT NOT NULL,

    CONSTRAINT "positions_sectors_pkey" PRIMARY KEY ("position_id", "sector_id"),
    CONSTRAINT "positions_sectors_position_id_fkey" FOREIGN KEY ("position_id") REFERENCES "positions"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "positions_sectors_sector_id_fkey" FOREIGN KEY ("sector_id") REFERENCES "sectors"("id") ON DELETE CASCADE ON UPDATE CASCADE
);


-- Tabela: employees
CREATE TABLE "employees" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "corporate_email" TEXT NOT NULL,
    "sector_id" TEXT NOT NULL,
    "position_id" TEXT NOT NULL,
    "user_id" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "employees_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "employees_corporate_email_key" UNIQUE ("corporate_email"),
    CONSTRAINT "employees_user_id_key" UNIQUE ("user_id"),
    CONSTRAINT "employees_sector_id_fkey" FOREIGN KEY ("sector_id") REFERENCES "sectors"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "employees_position_id_fkey" FOREIGN KEY ("position_id") REFERENCES "positions"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "employees_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE
);


-- Tabela: pendencies
CREATE TABLE "pendencies" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "type" "PendencyType" NOT NULL,
    "status" "PendencyStatus" NOT NULL DEFAULT 'PENDENTE',
    "priority" "Priority" NOT NULL DEFAULT 'MEDIA',
    "origin_type" "OriginType" NOT NULL,
    "origin_os_id" TEXT,
    "created_by" TEXT NOT NULL,
    "responsible_id" TEXT,
    "responsible_sector_id" TEXT,
    "conclusion_text" TEXT,
    "conclusion_type" "ConclusionType",
    "due_date" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMP(3),

    CONSTRAINT "pendencies_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "pendencies_origin_os_id_fkey" FOREIGN KEY ("origin_os_id") REFERENCES "service_orders"("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "pendencies_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "pendencies_responsible_id_fkey" FOREIGN KEY ("responsible_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "pendencies_responsible_sector_id_fkey" FOREIGN KEY ("responsible_sector_id") REFERENCES "sectors"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- Indices Operacionais
CREATE INDEX "pendencies_status_idx" ON "pendencies"("status");
CREATE INDEX "pendencies_responsible_id_idx" ON "pendencies"("responsible_id");
CREATE INDEX "pendencies_responsible_sector_id_idx" ON "pendencies"("responsible_sector_id");
CREATE INDEX "pendencies_origin_os_id_idx" ON "pendencies"("origin_os_id");


-- Tabela: pendency_history
CREATE TABLE "pendency_history" (
    "id" TEXT NOT NULL,
    "pendency_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "old_status" "PendencyStatus" NOT NULL,
    "new_status" "PendencyStatus" NOT NULL,
    "observation" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "pendency_history_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "pendency_history_pendency_id_fkey" FOREIGN KEY ("pendency_id") REFERENCES "pendencies"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "pendency_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Indices Operacionais
CREATE INDEX "pendency_history_pendency_id_idx" ON "pendency_history"("pendency_id");


-- ==============================================================================
-- 4. SEED INICIAL (Obrigatório)
-- ==============================================================================

-- Inserir Role ADMIN
INSERT INTO "roles" ("id", "name", "description", "is_system", "updated_at")
VALUES ('ADMIN', 'Administrador', 'Acesso total ao sistema', true, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

-- Inserir Usuário ADMIN Padrão
-- Senha hashada: $2b$10$L8wLY582D9C4m8M2UuKq1eRjDxvUn4YvShgJSeKh3OHHUC4O/umWK
INSERT INTO "users" ("id", "name", "email", "password_hash", "active", "updated_at")
VALUES (
    'admin-initial-id', 
    'Administrador do Sistema', 
    'ti@solucaolo.com.br', 
    '$2b$10$L8wLY582D9C4m8M2UuKq1eRjDxvUn4YvShgJSeKh3OHHUC4O/umWK', 
    true, 
    CURRENT_TIMESTAMP
)
ON CONFLICT ("email") DO NOTHING;

-- Vincular Usuário ao Role ADMIN
INSERT INTO "users_roles" ("user_id", "role_id")
SELECT id, 'ADMIN' FROM "users" WHERE email = 'ti@solucaolo.com.br'
ON CONFLICT ("user_id", "role_id") DO NOTHING;

